import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import { ThemeProvider } from "@/components/providers";
import { LoginDialogProvider } from "@/context/login-dialog-context";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={cn(
        "min-h-screen bg-background font-sans antialiased scroll-smooth",
        fontSans.variable
      )}
      suppressHydrationWarning
    >
      <body>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LoginDialogProvider>{children}</LoginDialogProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
