import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import {
  ConfirmDialogProvider,
  QueryProvider,
  ThemeProvider,
} from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { LoginDialogProvider } from "@/context/login-dialog-context";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={cn(
        "min-h-screen bg-background font-sans antialiased scroll-smooth",
        fontSans.variable
      )}
      suppressHydrationWarning
    >
      <body>
        <SessionProvider>
          <QueryProvider>
            <ConfirmDialogProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                // disableTransitionOnChange
              >
                <LoginDialogProvider>
                  {children}

                  <Toaster richColors />
                </LoginDialogProvider>
              </ThemeProvider>
            </ConfirmDialogProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
